version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: walletbud-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_DATABASE: WalletBudDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - wb-network
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  wildfly:
    build: .
    container_name: walletbud-web
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_NAME: WalletBudDB
      DB_USER: user
    networks:
      - wb-network
    ports:
      - "8000:8080"
    # depends_on:
    #   - database
    depends_on:
      database:
        condition: service_healthy

networks:
  wb-network:
    driver: bridge
